# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: "TTT"
description: 'Critical commentary on tech and society'
url: 'https://chandniverse.github.io'
baseurl: /

# Author
author:
  name: 'Chandni'
  url: 'https://twitter.com/chandniverse'

# Custom vars
github:
  repo: 'https://github.com/chandniverse/chandniverse.github.io'
