# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: 'Chandni's Website'
tagline: 'Technology Blog'
description: 'Critical commentary on tech and society'
url: 'https://chandniverse.github.io'
baseurl: '/'

author:
  name: 'Chandni'
  url: 'https://twitter.com/chandniverse'

paginate: 5

# GitHub Pages specific configuration
theme: 'jekyll-theme-primer'

# Custom vars
github:
  repo: 'https://github.com/chandniverse/chandniverse.github.io'
