# Site settings
title: Chandni Naidu Deadwyler
description: Product design, research, and strategy for data-driven workflows.
author: Chandni Naidu Deadwyler
email: chandni.naidu@outlook.com

url: "https://chandniverse.github.io"
baseurl: ""

# Build
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Posts
permalink: /blog/:slug/

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
